version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.0
  build:
    commands:
      - echo "Building application..."
      - zip -r app.zip .
      - mv app.zip /build/artifacts/
artifacts:
  files:
    - app.zip